regions:
  eu-west-1:
    shortname: eu
    vpc: vpc-f75fb790
    security_groups: sg-05f5615bfa38205ea, sg-8bcb5ff2
    subnets: subnet-932717cb, subnet-c1b94888, subnet-2a1de94d

  us-east-1:
    shortname: us
    vpc: vpc-d2bca9b4
    security_groups: sg-079aaedb6eff4030f, sg-277d4c58
    subnets: subnet-62bee007, subnet-1520f95d, subnet-dd638cf1