AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to create SNS entities for UPP"
Parameters:

  TagTeamDL:
    Type: String
    Description: Email address of the team used to tag objects
    Default: "universal.publishing.platform@ft.com"

  TagSystemCode:
    Type: String
    Description: The system code for the environment
    Default: upp

  TagEnvironmentType:
    Description: Tag detail for the Environment
    Type: String
    AllowedValues:
      - 'd'
      - 't'
      - 'p'
    Default: d

Resources:
  SNSAutomatedKeyRotation:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: teamDL
          Value: !Ref TagTeamDL
        - Key: SystemCode
          Value: !Ref TagSystemCode
        - Key: EnvironmentType
          Value: !Ref TagEnvironmentType
      TopicName: IAM-Automated-Key-Rotation-Notification-Topic

  SNSAutomatedKeyRotationPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: __default_policy_ID
        Statement:
        - Sid: __default_statement_ID
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - SNS:GetTopicAttributes
          - SNS:SetTopicAttributes
          - SNS:AddPermission
          - SNS:RemovePermission
          - SNS:DeleteTopic
          - SNS:Subscribe
          - SNS:ListSubscriptionsByTopic
          - SNS:Publish
          - SNS:Receive
          Resource: !Ref SNSAutomatedKeyRotation
          Condition:
            StringEquals:
              AWS:SourceOwner: !Ref AWS::AccountId
      Topics:
        - !Ref SNSAutomatedKeyRotation

  SNSRDSEvent:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: teamDL
          Value: !Ref TagTeamDL
        - Key: SystemCode
          Value: !Ref TagSystemCode
        - Key: EnvironmentType
          Value: !Ref TagEnvironmentType
      TopicName: RDS_Event-dev

  SNSRDSEventPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: __default_policy_ID
        Statement:
        - Sid: __default_statement_ID
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - SNS:GetTopicAttributes
          - SNS:SetTopicAttributes
          - SNS:AddPermission
          - SNS:RemovePermission
          - SNS:DeleteTopic
          - SNS:Subscribe
          - SNS:ListSubscriptionsByTopic
          - SNS:Publish
          - SNS:Receive
          Resource: !Ref SNSRDSEvent
          Condition:
            StringEquals:
              AWS:SourceOwner: !Ref AWS::AccountId
      Topics:
        - !Ref SNSRDSEvent

  SNSdynamodb:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: teamDL
          Value: !Ref TagTeamDL
        - Key: SystemCode
          Value: !Ref TagSystemCode
        - Key: EnvironmentType
          Value: !Ref TagEnvironmentType
      TopicName: dynamodb

  SNSdynamodbPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: __default_policy_ID
        Statement:
        - Sid: __default_statement_ID
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - SNS:GetTopicAttributes
          - SNS:SetTopicAttributes
          - SNS:AddPermission
          - SNS:RemovePermission
          - SNS:DeleteTopic
          - SNS:Subscribe
          - SNS:ListSubscriptionsByTopic
          - SNS:Publish
          - SNS:Receive
          Resource: !Ref SNSdynamodb
          Condition:
            StringEquals:
              AWS:SourceOwner: !Ref AWS::AccountId
      Topics:
        - !Ref SNSdynamodb

  SNSuppconceptpublishingprimary:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: teamDL
          Value: !Ref TagTeamDL
        - Key: SystemCode
          Value: !Ref TagSystemCode
        - Key: EnvironmentType
          Value: !Ref TagEnvironmentType
      TopicName: upp-concept-publishing-primary-k8s-SNSTopic

  SNSuppconceptpublishingprimaryPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: ConceptNotificationTopicPolicy
        Statement:
        - Sid: allow-s3-publish
          Effect: Allow
          Principal:
            AWS: "*"
          Action: sns:Publish
          Resource: !Ref SNSuppconceptpublishingprimary
          Condition:
            ArnLike:
              aws:SourceArn: arn:aws:s3:::upp-concept-normalised-store-k8s
        - Sid: allow-content-container-apps-publish
          Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/content-containers-apps"
          Action:
          - SNS:Publish
          - SNS:GetTopicAttributes
          Resource: !Ref SNSuppconceptpublishingprimary
      Topics:
        - !Ref SNSuppconceptpublishingprimary

  uppconceptpublishingSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Sub "arn:aws:sqs:eu-west-1:${AWS::AccountId}:upp-concept-publish-notifications-k8s-1"
      Protocol: sqs
      TopicArn: !Ref SNSuppconceptpublishingprimary

  SNSQueueOverflowAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: teamDL
          Value: !Ref TagTeamDL
        - Key: SystemCode
          Value: !Ref TagSystemCode
        - Key: EnvironmentType
          Value: !Ref TagEnvironmentType
      TopicName: upp-concept-publishing-primary-k8s-SQSConceptQueueOverflowAlarmTopic

  SNSQueueOverflowAlarmTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: __default_policy_ID
        Statement:
        - Sid: __default_statement_ID
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - SNS:GetTopicAttributes
          - SNS:SetTopicAttributes
          - SNS:AddPermission
          - SNS:RemovePermission
          - SNS:DeleteTopic
          - SNS:Subscribe
          - SNS:ListSubscriptionsByTopic
          - SNS:Publish
          - SNS:Receive
          Resource: !Ref SNSQueueOverflowAlarmTopic
          Condition:
            StringEquals:
              AWS:SourceOwner: !Ref AWS::AccountId
      Topics:
        - !Ref SNSQueueOverflowAlarmTopic

  SNSUPPConceptEventsDev:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: teamDL
          Value: !Ref TagTeamDL
        - Key: SystemCode
          Value: !Ref TagSystemCode
        - Key: EnvironmentType
          Value: !Ref TagEnvironmentType
      TopicName: upp-concept-events-k8s-SNSTopic


  UPPConceptEventsDevSQSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Sub "arn:aws:sqs:eu-west-1:${AWS::AccountId}:upp-concept-events-dev"
      Protocol: sqs
      TopicArn: !Ref SNSUPPConceptEventsDev

  UPPConceptEventsCECCIDevSQSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Sub "arn:aws:sqs:eu-west-1:${AWS::AccountId}:upp-concept-events-cecci-dev"
      Protocol: sqs
      TopicArn: !Ref SNSUPPConceptEventsDev
