# These settings determine the behaviour of runbook.md's Runbook Validator bot
# https://github.com/financial-times/runbook.md

# Everything below is optional

runbooks:
    # All available settings are listed below

    # Disable checks for this repo
    # defaults to `false`
    disabled: false

    ### SUPPORT FOR MULTIPLE RUNBOOKS IN A SINGLE REPOSITORY

    # Fail checks if `any` | `all` | `none` runbooks fail validation
    # defaults to `any`
    failOn: any

    ### SUPPORT FOR UPDATING BIZ-OPS

    # Update valid Biz-Ops runbooks on merge to a specific branch
    #### IF YOUR DEPLOYMENTS ARE AUTOMATED (CircleCI, Heroku Pipelines)
    #### PLEASE INTEGRATE WITH CHANGE-API INSTEAD
    #### https://github.com/Financial-Times/change-api#change-api---v2
    # defaults to `false`
    updateOnMerge: true

    # Merges to this branch trigger Biz-Ops updates updateOnMerge is `true`
    # defaults to `master`
    updateBranch: master

    ### UPDATING BIZ-OPS REQUIRES EACH RUNBOOK TO BE TIED TO A VALID SYSTEM CODE
    # Mappings between paths and system codes
    # unless a custom mapping is specified here
    # runbook.md tries to parse the system code from the runbook's filename (format: my-sys-code_runbook.md)
    systemCodes:
        # paths are relative to root, omitting ./ (case-insensitive)
        pac-aurora: runbooks/pac-aurora-runbook.md
        upp-content-es-cluster: runbooks/upp-content-es-runbook.md
        upp-ccf-content-es-cluster: runbooks/upp-ccf-content-es-cluster-runbook.md
        upp-concept-publish-provisioner: runbooks/upp-concept-publishing-provisioner-runbook.md
        upp-elasticsearch-provisioner: runbooks/upp-es-provisioner-runbook.md
        upp-jenkins-provisioner: runbooks/upp-jenkins-provisioner-runbook.md
        upp-jenkins: runbooks/upp-jenkins-runbook.md
        pac-aurora-provisoner: runbooks/pac-aurora-provisoner-runbook.md
        content-fluentd-stream: runbooks/content-fluentd-kinesis-runbook.md
        ccf-client-settings-dynamodb: runbooks/ccf-client-settings-dynamodb-runbook.md
        upp-factset-store: runbooks/upp-factset-store-runbook.md
        upp-concept-carousel-queue-provisioner: runbooks/upp-concept-carousel-queue-provisioner.md
        upp-concept-carousel-queue: runbooks/upp-concept-carousel-queue.md
        upp-ontotext-backup-aurora: runbooks/upp-ontotext-backup-aurora.md
        upp-concept-events-queue: runbooks/upp-concept-events-queue-runbook.md
        concept-elasticsearch-cluster: runbooks/concept-elasticsearch-cluster-runbook.md
        upp-enriched-content-store: runbooks/upp-enriched-content-store-runbook.md
