- hosts: all

  vars:
    cluster_name: "{{cf_template}}-{{delivery_cluster}}"

  vars_files:
    - vault_{{aws_account}}.yml

  tasks:
    - name: Get the ElasticSearch endpoint
      cloudformation_facts:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        region: "{{aws_default_region}}"
        stack_name: "{{cluster_name}}"
      register: es_stack_output

    - debug:
        msg: "{{es_stack_output}}"

    - name: Save ElasticSearch cluster endpoint as a variable
      set_fact:
        es_endpoint: "{{es_stack_output['ansible_facts']['cloudformation'][cluster_name]['stack_outputs']['ESClusterEndpoint']}}"

    - debug:
        msg: "{{es_endpoint}}"

    - name: Create ES snapshot
      uri:
        url: "http://{{es_endpoint}}/_snapshot/index-backups/autobackup-{{ ansible_date_time.iso8601 | lower }}?wait_for_completion=true"
        method: PUT
      register: es_backup_output
      when:
        - delete_s3_bucket != "true"

    - debug:
        msg: "{{es_backup_output}}"

    - name: Delete ElasticSearch cluster
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        region: "{{aws_default_region}}"
        stack_name: "{{cluster_name}}"
        state: "absent"
      register: es_stack_output

    - debug:
        msg: "{{es_stack_output}}"

    - name: Delete cluster CNAME
      include: tasks/delete_cname.yml

    - name: Delete S3 bucket (if requested)
      include: tasks/delete_s3_bucket.yml
      when:
        - delete_s3_bucket == "true"
