#!/usr/bin/python

import sys, re

if __name__ == "__main__":
  for line in sys.stdin:
    m = re.match('.*ft.{3}(?P<clusterid>\w{8})-\w{5}-..-..*', line)
    if m and m.groupdict()["clusterid"]:
      print m.groupdict()["clusterid"]

