---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys a Aurora cluster for PAC.

Metadata:
    AWS::CloudFormation::Interface:
        - Label: FT standard tagging
          Parameters:
             - TagEnvironment
             - TagTeamDL
             - TagSystemCode
             - TagIpCode
             - TagDescription
             - TagName

Parameters:
    DBVPC:
        Description: Choose which VPC the Aurora DB should be deployed TagStopSchedule
        Type: AWS::EC2::VPC::Id

    DBSecurityGroups:
        Description: Select the Security group to allow access to the Aurora instance
        Type: List<AWS::EC2::SecurityGroup::Id>

    DBInstanceType:
        Description: The instance type to use for the database
        Type: String
        AllowedValues:
            - db.t2.small
            - db.t2.medium
            - db.r3.large
            - db.r3.xlarge
            - db.r3.2xlarge
            - db.r3.4xlarge
            - db.r3.8xlarge
        Default: db.t2.small

    DBInstanceMasterUsername:
        Description: The master Username for the database
        Type: String
        MinLength: 1
        MaxLength: 16
        AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
        ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

    DBInstanceMasterPassword:
        Description: The master password for the database
        NoEcho: true
        Type: String
        MinLength: 10
        MaxLength: 41
        AllowedPattern: '[a-zA-Z0-9]*'
        ConstraintDescription: must contain only alphanumeric characters.

    DBInstanceDBName:
        Description: The string that will be prefixed to each instance name
        Type: String
        MinLength: 1
        MaxLength: 16
        AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
        ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

    DBParameterGroup:
        Description: The DBParameterGroup name to use
        Type: String

    DBClusterParameterGroup:
        Description: The DBClusterParameterGroup name to use
        Type: String

    DBSubnetGroup:
        Description: The DBSubnetGroup name to use
        Type: String

    DBBackupRetentionPeriod:
        Description: Backup retention period in days to use
        Type: Number
        MinValue: 1
        MaxValue: 35

    SourceSnapshot:
        Description: The ARN of DB snapshot from which you are creating the DB cluster
        Type: String

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    TagEnvironment:
        Description: Tag detail for the Environment
        Type: String
        AllowedValues:
            - 't'
            - 'p'
            - 'd'
        Default: t

    TagTeamDL:
        Description: Tag of the TeamDL
        Type: String
        AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
        ConstraintDescription: There must be a valid email address for the TeamDL
        Default: universal.publishing.platform@ft.com

    TagSystemCode:
        Description: The system code for the environment
        Type: String
        Default: pac

    TagIpCode:
        Description: The environment ipCode
        Type: String
        AllowedPattern: '[P][0-9]*'
        Default: P196

    TagDescription:
        Description: Tag detail for the describing the instance
        Type: String
        Default: PAC Aurora

    TagName:
        Description: Tag detail for the Name used in the console of the instance
        Type: String
        Default: PAC Aurora

Conditions:
    UseDBSnapshot: !Not [!Equals [!Ref SourceSnapshot, ""]]
    DoNotUseDBSnapshot: !Not [Condition: UseDBSnapshot]

Resources:
    DBCluster:
        Type: AWS::RDS::DBCluster
        Condition: DoNotUseDBSnapshot
        Properties:
            Engine: aurora
            DatabaseName: !Ref DBInstanceDBName
            DBSubnetGroupName: !Ref DBSubnetGroup
            MasterUsername: !Ref DBInstanceMasterUsername
            MasterUserPassword: !Ref DBInstanceMasterPassword
            VpcSecurityGroupIds: !Ref DBSecurityGroups
            DBClusterParameterGroupName: !Ref DBClusterParameterGroup
            BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
            Tags:
                - Key: environment
                  Value: !Ref TagEnvironment
                - Key: teamDL
                  Value: !Ref TagTeamDL
                - Key: systemCode
                  Value: !Ref TagSystemCode
                - Key: ipCode
                  Value: !Ref TagIpCode
                - Key: description
                  Value: !Ref TagDescription
                - Key: name
                  Value: !Sub ${TagName} - ${EnvironmentName}

    DBClusterFromSnapshot:
        Type: AWS::RDS::DBCluster
        Condition: UseDBSnapshot
        Properties:
            Engine: aurora
            DatabaseName: !Ref DBInstanceDBName
            DBSubnetGroupName: !Ref DBSubnetGroup
            VpcSecurityGroupIds: !Ref DBSecurityGroups
            DBClusterParameterGroupName: !Ref DBClusterParameterGroup
            BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
            SnapshotIdentifier: !Ref SourceSnapshot
            Tags:
                - Key: environment
                  Value: !Ref TagEnvironment
                - Key: teamDL
                  Value: !Ref TagTeamDL
                - Key: systemCode
                  Value: !Ref TagSystemCode
                - Key: ipCode
                  Value: !Ref TagIpCode
                - Key: description
                  Value: !Ref TagDescription
                - Key: name
                  Value: !Sub ${TagName} - ${EnvironmentName}

    DBPrimaryInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            DBClusterIdentifier:
              !If [UseDBSnapshot, !Ref DBClusterFromSnapshot, !Ref DBCluster]
            DBInstanceClass: !Ref DBInstanceType
            Engine: aurora
            DBParameterGroupName: !Ref DBParameterGroup
            DBSubnetGroupName: !Ref DBSubnetGroup
            DBInstanceIdentifier: !Sub '${EnvironmentName}-1-${AWS::Region}'
            PubliclyAccessible: false
            Tags:
                - Key: environment
                  Value: !Ref TagEnvironment
                - Key: teamDL
                  Value: !Ref TagTeamDL
                - Key: systemCode
                  Value: !Ref TagSystemCode
                - Key: ipCode
                  Value: !Ref TagIpCode
                - Key: description
                  Value: !Ref TagDescription
                - Key: name
                  Value: !Sub ${TagName} - ${EnvironmentName}

    DBReplicaInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            DBClusterIdentifier:
              !If [UseDBSnapshot, !Ref DBClusterFromSnapshot, !Ref DBCluster]
            DBInstanceClass: !Ref DBInstanceType
            Engine: aurora
            DBParameterGroupName: !Ref DBParameterGroup
            DBSubnetGroupName: !Ref DBSubnetGroup
            DBInstanceIdentifier: !Sub '${EnvironmentName}-2-${AWS::Region}'
            PubliclyAccessible: false
            Tags:
                - Key: environment
                  Value: !Ref TagEnvironment
                - Key: teamDL
                  Value: !Ref TagTeamDL
                - Key: systemCode
                  Value: !Ref TagSystemCode
                - Key: ipCode
                  Value: !Ref TagIpCode
                - Key: description
                  Value: !Ref TagDescription
                - Key: name
                  Value: !Sub ${TagName} - ${EnvironmentName}

Outputs:
    DBCluster:
        Description: A reference to the DBCluster
        Value:
          !If [UseDBSnapshot, !Ref DBClusterFromSnapshot, !Ref DBCluster]

    DBHostname:
        Description: A reference to the DBCluster hostname
        Value:
          !If [UseDBSnapshot, !GetAtt [DBClusterFromSnapshot, Endpoint.Address], !GetAtt [DBCluster, Endpoint.Address]]

    DBPort:
        Description: A reference to the DBCluster port
        Value:
          !If [UseDBSnapshot, !GetAtt [DBClusterFromSnapshot, Endpoint.Port], !GetAtt [DBCluster, Endpoint.Port]]

    DBInstanceName:
        Description: A reference to the DBPrimaryInstance Name
        Value: !Sub '${EnvironmentName}-primary-${AWS::Region}'
