---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys a DB subnet group in the US

Metadata:
  AWS::CloudFormation::Interface:
    - Label: FT standard tagging
      Parameters:
        - TagEnvironment
        - TagTeamDL
        - TagSystemCode
        - TagIpCode
        - TagDescription
        - TagName

Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    TagEnvironment:
        Description: Tag detail for the Environment
        Type: String
        AllowedValues:
            - 't'
            - 'p'
        Default: t

    TagTeamDL:
        Description: Tag of the TeamDL
        Type: String
        AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
        ConstraintDescription: There must be a valid email address for the TeamDL
        Default: universal.publishing.platform@ft.com

    TagSystemCode:
        Description: The system code for the environment
        Type: String
        Default: pac

    TagIpCode:
        Description: The environment ipCode
        Type: String
        AllowedPattern: '[P][0-9]*'
        Default: P196

    TagDescription:
        Description: Tag detail for the describing the instance
        Type: String
        Default: PAC Aurora

    TagName:
        Description: Tag detail for the Name used in the console of the instance
        Type: String
        Default: PAC Aurora

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Join ['', [!Ref EnvironmentName, ' subnet group']]
      SubnetIds:
        - 'subnet-d63d859e'
        - 'subnet-a8dc1384'
        - 'subnet-f9fcc99c'
      Tags:
        - Key: environment
          Value: !Ref TagEnvironment
        - Key: teamDL
          Value: !Ref TagTeamDL
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: ipCode
          Value: !Ref TagIpCode
        - Key: description
          Value: !Ref TagDescription
        - Key: name
          Value: !Sub ${TagName} - ${EnvironmentName}

Outputs:
  DBSubnetGroup:
    Description: A reference to the DBSubnetGroup
    Value: !Ref DBSubnetGroup
