---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys a RDS Aurora cluster.

Metadata:
    AWS::CloudFormation::Interface:
        - Label: FT standard tagging
          Parameters:
             - TagEnvironment
             - TagTeamDL
             - TagSystemCode
             - TagIpCode
             - TagDescription
             - TagName

Parameters:
    DBVPC: 
        Description: Choose which VPC the Aurora DB should be deployed TagStopSchedule
        Type: AWS::EC2::VPC::Id

    DBSecurityGroup:
        Description: Select the Security group to allow access to the Aurora instance
        Type: AWS::EC2::SecurityGroup::Id

    DBInstanceType:
        Description: The instance type to use for the database
        Type: String
        AllowedValues:
            - db.t2.small
            - db.t2.medium
            - db.r3.large
            - db.r3.xlarge
            - db.r3.2xlarge
            - db.r3.4xlarge
            - db.r3.8xlarge
        Default: db.t2.small

    DBUsername: 
        Description: The master Username for the database
        Type: String
        MinLength: 1
        MaxLength: 16
        AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
        ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
    
    DBPassword:
        Description: The master password for the database
        NoEcho: true
        Type: String
        MinLength: 10
        MaxLength: 41
        AllowedPattern: '[a-zA-Z0-9]*'
        ConstraintDescription: must contain only alphanumeric characters.

    DBBackupRetentionPeriod:
        Type: String
        Default: 7
        AllowedValues:
            - 1
            - 7
    
    DBIdentifierNameMaster:
        Description: The string that will be prefixed to each instance name
        Type: String
        MinLength: 1
        MaxLength: 16
        AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
        ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

    EnvironmentName:
        Description: An environment name that will be prefixed to resource namesqq
        Type: String

    TagEnvironment:
        Description: Tag detail for the Environment
        Type: String
        AllowedValues:
            - 't'
            - 'p'
        Default: t

    TagTeamDL:
        Description: Tag of the TeamDL
        Type: String
        AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
        ConstraintDescription: There must be a valid email address for the TeamDL
        Default: universal.publishing.platform@ft.com

    TagSystemCode:
        Description: The system code for the environment
        Type: String
        Default: pac

    TagIpCode:
        Description: The environment ipCode
        Type: String
        AllowedPattern: '[P][0-9]*'
        Default: P196

    TagDescription:
        Description: Tag detail for the describing the instance
        Type: String
        Default: PAC Aurora

    TagName:
        Description: Tag detail for the Name used in the console of the instance
        Type: String
        Default: PAC Aurora

Resources:
    DBSubnetGroup:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: !Join ['', [!Ref EnvironmentName, ' subnet group']]
            SubnetIds:
                - 'subnet-932717cb'
                - 'subnet-c1b94888'
                - 'subnet-2a1de94d'
            Tags:
              - Key: environment
                Value: !Ref TagEnvironment
              - Key: teamDL
                Value: !Ref TagTeamDL
              - Key: systemCode
                Value: !Ref TagSystemCode
              - Key: ipCode
                Value: !Ref TagIpCode
              - Key: description
                Value: !Ref TagDescription
              - Key: name
                Value: !Sub ${TagName} - ${EnvironmentName}

    DBCluster:
        Type: AWS::RDS::DBCluster
        Properties:
            Engine: aurora
            DatabaseName: !Ref DBIdentifierNameMaster
            DBSubnetGroupName: !Ref DBSubnetGroup
            MasterUsername: !Ref DBUsername
            MasterUserPassword: !Ref DBPassword
            VpcSecurityGroupIds:
                - Ref: DBSecurityGroup
            DBClusterParameterGroupName: !Ref DBClusterParameterGroup
            Tags:
                - Key: environment
                  Value: !Ref TagEnvironment
                - Key: teamDL
                  Value: !Ref TagTeamDL
                - Key: systemCode
                  Value: !Ref TagSystemCode
                - Key: ipCode
                  Value: !Ref TagIpCode
                - Key: description
                  Value: !Ref TagDescription
                - Key: name
                  Value: !Sub ${TagName} - ${EnvironmentName}

    DBInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            DBClusterIdentifier: !Ref DBCluster
            DBInstanceIdentifier: !Sub ${EnvironmentName}
            DBName: !Ref DBIdentifierNameMaster
            DBInstanceClass: !Ref DBInstanceType
            Engine: aurora
            DBParameterGroupName: !Ref DBParameterGroup
            DBSubnetGroupName: !Ref DBSubnetGroup
            PubliclyAccessible: false
            MultiAZ: true
            CopyTagsToSnapshot: true
            BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
            Tags:
                - Key: environment
                  Value: !Ref TagEnvironment
                - Key: teamDL
                  Value: !Ref TagTeamDL
                - Key: systemCode
                  Value: !Ref TagSystemCode
                - Key: ipCode
                  Value: !Ref TagIpCode
                - Key: description
                  Value: !Ref TagDescription
                - Key: name
                  Value: !Sub ${TagName} - ${EnvironmentName}

    DBClusterParameterGroup:
        Type: AWS::RDS::DBClusterParameterGroup
        Properties:
            Description: !Join ['', [!Ref EnvironmentName, ' cluster parameter group']]
            Family: aurora5.6
            Parameters:
                binlog_format: 'MIXED'
    
    DBParameterGroup:
        Type: AWS::RDS::DBParameterGroup
        Properties:
            Description: !Join ['', [!Ref EnvironmentName, ' parameter group']]
            Family: aurora5.6

Outputs:
    DBHostAndPort: 
        Description: A reference to the DBInstance connection string
        Value: !Join ['', [!GetAtt [DBInstance, Endpoint.Address], ':', !GetAtt [DBInstance, Endpoint.Port], '/', !Ref DBIdentifierNameMaster]]

    DBHostname: 
        Description: A reference to the DBInstance hostname
        Value: !GetAtt [DBInstance, Endpoint.Address]

    DBPort: 
        Description: A reference to the DBInstance port
        Value: !GetAtt [DBInstance, Endpoint.Port]