AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to create SQS entities for UPP"
Parameters:

  TagTeamDL:
    Type: String
    Description: Email address of the team used to tag objects
    Default: "universal.publishing.platform@ft.com"

  TagSystemCode:
    Type: String
    Description: The system code for the environment
    Default: upp

Resources:
  uppconceptcarouselqueuek8sprod:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      QueueName: "upp-concept-carousel-queue-k8s-prod"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: p

  uppconceptcarouselqueuek8sstaging:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      QueueName: "upp-concept-carousel-queue-k8s-staging"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: t

  uppconcepteventsdeadletterprod:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 0
      QueueName: "upp-concept-events-deadletter-prod"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: p

  uppconcepteventsdeadletterstaging:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 0
      QueueName: "upp-concept-events-deadletter-staging"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: t


  uppconcepteventsprod:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      MessageRetentionPeriod: 691200 #8 days
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt uppconcepteventsdeadletterprod.Arn
        maxReceiveCount : 5
      QueueName: "upp-concept-events-prod"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: p

  uppconcepteventsstaging:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      MessageRetentionPeriod: 691200 #8 days
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt uppconcepteventsdeadletterstaging.Arn
        maxReceiveCount : 5
      QueueName: "upp-concept-events-staging"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: t

  uppconceptpublishdeadletterk8sprod1:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 0
      QueueName: "upp-concept-publish-dead-letter-k8s-prod-1"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: p

  uppconceptpublishdeadletterk8sstaging1:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 0
      QueueName: "upp-concept-publish-dead-letter-k8s-staging-1"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: t

  uppconceptpublishnotificationsk8sprod1:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt uppconceptpublishdeadletterk8sprod1.Arn
        maxReceiveCount : 5
      QueueName: "upp-concept-publish-notifications-k8s-prod-1"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: p

  uppconceptpublishnotificationsk8sstaging1:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt uppconceptpublishdeadletterk8sstaging1.Arn
        maxReceiveCount : 5
      QueueName: "upp-concept-publish-notifications-k8s-staging-1"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: t

  UPPConceptEventsCECCIStagingDeadLetter:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 0
      QueueName: "upp-concept-events-cecci-staging-dead-letter"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: 't'

  UPPConceptEventsCECCIStaging:
    Type: AWS::SQS::Queue
    Description: Queue used by cm-enriched-content-concept-ingester
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt UPPConceptEventsCECCIStagingDeadLetter.Arn
        maxReceiveCount : 5
      QueueName: "upp-concept-events-cecci-staging"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: 't'

  UPPConceptEventsCECCIProdDeadLetter:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 0
      QueueName: "upp-concept-events-cecci-prod-dead-letter"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: 'p'

  UPPConceptEventsCECCIProd:
    Type: AWS::SQS::Queue
    Description: Queue used by cm-enriched-content-concept-ingester
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt UPPConceptEventsCECCIProdDeadLetter.Arn
        maxReceiveCount : 5
      QueueName: "upp-concept-events-cecci-prod"
      Tags:
        - Key: systemCode
          Value: !Ref TagSystemCode
        - Key: TagTeamDL
          Value: !Ref TagTeamDL
        - Key: environment
          Value: 'p'

  uppconceptcarouselqueuek8sprodPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: uppconceptcarouselqueuek8sprod
      PolicyDocument:
        Version: "2012-10-17"
        Id: ConceptCarouselQueuePolicy
        Statement:
          -
           Sid: "communicate-with-carousel-queue"
           Effect: Allow
           Principal:
             AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/content-containers-apps"
           Action: "SQS:*"
           Resource: !GetAtt uppconceptcarouselqueuek8sprod.Arn

  uppconceptcarouselqueuek8sstagingPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: uppconceptcarouselqueuek8sstaging
      PolicyDocument:
        Version: "2012-10-17"
        Id: ConceptCarouselQueuePolicy
        Statement:
          -
           Sid: "communicate-with-carousel-queue"
           Effect: Allow
           Principal:
             AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/content-containers-apps-staging"
           Action: "SQS:*"
           Resource: !GetAtt uppconceptcarouselqueuek8sstaging.Arn

  uppconcepteventsprodPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: uppconcepteventsprod
      PolicyDocument:
        Version: "2012-10-17"
        Id: ConceptNotificationQueuePolicy
        Statement:
          -
           Sid: "receive-from-sns"
           Effect: Allow
           Principal:
             AWS: "*"
           Action: "SQS:SendMessage"
           Resource: !GetAtt uppconcepteventsprod.Arn
           Condition:
             ArnLike:
               "aws:SourceArn": !Sub "arn:aws:sns:eu-west-1:${AWS::AccountId}:upp-concept-events-k8s-prod-SNSTopic"

  uppconcepteventsstagingPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: uppconcepteventsstaging
      PolicyDocument:
        Version: "2012-10-17"
        Id: ConceptNotificationQueuePolicy
        Statement:
          -
           Sid: "receive-from-sns"
           Effect: Allow
           Principal:
             AWS: "*"
           Action: "SQS:SendMessage"
           Resource: !GetAtt uppconcepteventsstaging.Arn
           Condition:
             ArnLike:
               "aws:SourceArn": !Sub "arn:aws:sns:eu-west-1:${AWS::AccountId}:upp-concept-events-k8s-staging-SNSTopic"

  uppconceptpublishnotificationsk8sprod1Policy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: uppconceptpublishnotificationsk8sprod1
      PolicyDocument:
        Version: "2012-10-17"
        Id: ConceptNotificationQueuePolicy
        Statement:
          -
           Sid: "receive-from-sns"
           Effect: Allow
           Principal:
             AWS: "*"
           Action: "SQS:SendMessage"
           Resource: !GetAtt uppconceptpublishnotificationsk8sprod1.Arn
           Condition:
             ArnLike:
               "aws:SourceArn": !Sub "arn:aws:sns:eu-west-1:${AWS::AccountId}:upp-concept-publishing-primary-k8s-prod-SNSTopic-*"
          -
           Sid: "communicate-with-sqs"
           Effect: Allow
           Principal:
             AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/content-containers-apps"
           Action: "SQS:*"
           Resource: !GetAtt uppconceptpublishnotificationsk8sprod1.Arn

  uppconceptpublishnotificationsk8sstaging1Policy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: uppconceptpublishnotificationsk8sstaging1
      PolicyDocument:
        Version: "2012-10-17"
        Id: ConceptNotificationQueuePolicy
        Statement:
          -
           Sid: "receive-from-sns"
           Effect: Allow
           Principal:
             AWS: "*"
           Action: "SQS:SendMessage"
           Resource: !GetAtt uppconceptpublishnotificationsk8sstaging1.Arn
           Condition:
             ArnLike:
               "aws:SourceArn": !Sub "arn:aws:sns:eu-west-1:${AWS::AccountId}:upp-concept-publishing-primary-k8s-staging-SNSTopic-*"
          -
           Sid: "communicate-with-sqs"
           Effect: Allow
           Principal:
             AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/content-containers-apps-staging"
           Action: "SQS:*"
           Resource: !GetAtt uppconceptpublishnotificationsk8sstaging1.Arn

  UPPConceptEventsCECCIStagingPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: UPPConceptEventsCECCIStaging
      PolicyDocument:
        Version: "2012-10-17"
        Id: UppConceptEventsCECCIStagingQueuePolicy
        Statement:
          -
           Sid: "receive-from-sns"
           Effect: Allow
           Principal:
             AWS: "*"
           Action: "SQS:SendMessage"
           Resource: !GetAtt UPPConceptEventsCECCIStaging.Arn
           Condition:
             ArnLike:
               "aws:SourceArn": !Sub "arn:aws:sns:eu-west-1:${AWS::AccountId}:upp-concept-events-k8s-staging-SNSTopic"

  UPPConceptEventsCECCIProdPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: UPPConceptEventsCECCIProd
      PolicyDocument:
        Version: "2012-10-17"
        Id: UppConceptEventsCECCIProdQueuePolicy
        Statement:
          -
           Sid: "receive-from-sns"
           Effect: Allow
           Principal:
             AWS: "*"
           Action: "SQS:SendMessage"
           Resource: !GetAtt UPPConceptEventsCECCIProd.Arn
           Condition:
             ArnLike:
               "aws:SourceArn": !Sub "arn:aws:sns:eu-west-1:${AWS::AccountId}:upp-concept-events-k8s-prod-SNSTopic"
