AWSTemplateFormatVersion: 2010-09-09
Description: >
  Template to spin-up an Elasticsearch cluster for upp-concepts

Parameters:
  EnvironmentType:
    Description: Environment type (Test or Production).
    Type: String
    AllowedValues:
      - 't'
      - 'p'
    Default: t
  ClusterName:
    Description: Which delivery cluster this ES service is attached to (eg. prod-uk).  Must be no more than 12 characters.
    Type: String

Resources:
  ElasticsearchDomain:
    Type: "AWS::Elasticsearch::Domain"
    Properties:
      DomainName: !Ref ClusterName
      ElasticsearchVersion: "1.5"
      ElasticsearchClusterConfig:
        InstanceCount: "4"
        ZoneAwarenessEnabled: "true"
        InstanceType: "r3.large.elasticsearch"
        DedicatedMasterType: "m3.medium.elasticsearch"
        DedicatedMasterCount: "3"
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 25
        VolumeType: "gp2"
      SnapshotOptions:
        AutomatedSnapshotStartHour: "0"
#      AccessPolicies:
#        Version: "2012-10-17"
#        Statement:
#          -
#            Effect: "Allow"
#            Principal:
#              AWS: "arn:aws:iam::027104099916:user/content-containers-apps"
#            Action: "es:*"
#            Resource: !Join [ "", [ "arn:aws:es:eu-west-1:027104099916:domain/", !Ref ClusterName, "/*" ] ]
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: "arn:aws:es:eu-west-1:810385116814:domain/upp-concepts-cf-testing/*"
            Condition:
              IpAddress:
                aws:SourceIP: "82.136.1.214/32"
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: "true"
      Tags:
        - Key: env
          Value: !Ref EnvironmentType
        - Key: teamDL
          Value: "universal.publishing.platform@ft.com"
        - Key: systemCode
          Value: !Ref ClusterName
        - Key: ipcode
          Value: "P490"
        - Key: description
          Value: !Ref ClusterName

Outputs:
  ESClusterEndpoint:
    Description: The ElasticSearch cluster endpoint
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint
