- hosts: all

  tasks:
    - name: Delete Database Stack
      when: "{{decom_dbs|lower}} == true"
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        region: "{{aws_default_region}}"
        stack_name: "upp-concept-publishing-databases-{{environment_tag}}"
        state: "absent"
      register: concept_pub_db_stack_output

    - debug:
        msg: "{{concept_pub_db_stack_output}}"

    - name: Delete Primary Queue Stack
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        region: "{{aws_default_region}}"
        stack_name: "upp-concept-publishing-primary-{{environment_tag}}"
        state: "absent"
      register: primary_concept_pub_stack_output

    - debug:
        msg: "{{primary_concept_pub_stack_output}}"

    - name: Delete Secondary Queue stack
      when: "{{is_multi_region|lower}} == true"
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        region: "{{aws_secondary_region}}"
        stack_name: "upp-concept-publishing-secondary-{{environment_tag}}"
        state: "absent"
      register: secondary_concept_pub_stack_output

    - debug:
        msg: "{{secondary_concept_pub_stack_output}}"

    - name: Delete Subscription stack
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        region: "eu-west-1"
        stack_name: "upp-concept-publishing-subscriptions-{{environment_tag}}"
        state: "absent"
      register: concept_sub_stack_output

    - debug:
        msg: "{{concept_sub_stack_output}}"
