- hosts: all

  vars_files:
    - vault.yml

  tasks:
    - name: Create Concept Publishing stack
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        stack_name: "upp-concept-publishing-{{environment_tag}}"
        state: "present"
        region: "{{aws_default_region}}"
        template: "/cloudformation/sns-sqs-cf.yml"
        template_parameters:
          EnvironmentTag: "{{environment_tag}}"
          IsMultiRegion: "{{ismultiregion}}"
        tags:
          environment: "{{environment_type}}"
          systemCode: "upp"
          teamDL: "universal.publishing.platform@ft.com"
          description: "Concept Publishing Cloudformation Stack - {{environment_tag}}"
      register: concept_pub_stack_output

    - debug:
        msg: "{{concept_pub_stack_output}}"