- hosts: all

  tasks:
    - name: Create Primary Queues Concept Publishing Stack
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        stack_name: "upp-concept-publishing-primary-{{environment_tag}}"
        state: "present"
        region: "{{aws_default_region}}"
        template: "/cloudformation/sns-sqs-cf-single-region.yml"
        template_parameters:
          EnvironmentTag: "{{environment_tag}}"
          EnvironmentType: "{{environment_type}}"
          SQSConceptQueueMaxDepth: "{{sqs_concept_max_depth}}"
        tags:
          environment: "{{environment_type}}"
          systemCode: "upp"
          teamDL: "universal.publishing.platform@ft.com"
          description: "Concept Publishing Primary Queues Stack - {{environment_tag}}"
      register: primary_concept_pub_stack_output

    - debug:
        msg: "{{primary_concept_pub_stack_output}}"

    - name: Save primary sqs arn and topic arns as variables
      set_fact:
        SNSConceptTopicARN: "{{primary_concept_pub_stack_output.stack_outputs.ConceptTopicARN}}"

    - name: Create Databases for Concept Publishing Stack
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        stack_name: "upp-concept-publishing-databases-{{environment_tag}}"
        state: "present"
        region: "{{aws_default_region}}"
        template: "/cloudformation/databases.yml"
        template_parameters:
          EnvironmentTag: "{{environment_tag}}"
          EnvironmentType: "{{environment_type}}"
          SNSTopicARN: "{{SNSConceptTopicARN}}"
        tags:
          environment: "{{environment_type}}"
          systemCode: "upp"
          teamDL: "universal.publishing.platform@ft.com"
          description: "Concept Publishing Database Stack - {{environment_tag}}"

    - name: Create Secondary Queues Concept Publishing Stack
      when: "{{is_multi_region|lower}} == true"
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        stack_name: "upp-concept-publishing-secondary-{{environment_tag}}"
        state: "present"
        region: "{{aws_secondary_region}}"
        template: "/cloudformation/sns-sqs-cf-multi-region.yml"
        template_parameters:
          EnvironmentTag: "{{environment_tag}}"
          EnvironmentType: "{{environment_type}}"
          Region: "{{aws_secondary_region}}"
          SNSTopicARN: "{{SNSConceptTopicARN}}"
          SQSConceptQueueMaxDepth: "{{sqs_concept_max_depth}}"
        tags:
          environment: "{{environment_type}}"
          systemCode: "upp"
          teamDL: "universal.publishing.platform@ft.com"
          description: "Concept Publishing Secondary Queues Stack - {{environment_tag}}"
      register: secondary_concept_pub_stack_output

    - debug:
        msg: "{{secondary_concept_pub_stack_output}}"

    - name: Save secondary sqs arn as a variable
      when: "{{is_multi_region|lower}} == true"
      set_fact:
        SQSSecondaryConceptARN: "{{secondary_concept_pub_stack_output.stack_outputs.SecondaryConceptARN}}"

    - name: Subscribe queues to topic
      when: "{{is_multi_region|lower}} == true"
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        stack_name: "upp-concept-publishing-subscriptions-{{environment_tag}}"
        state: "present"
        region: "{{aws_default_region}}"
        template: "/cloudformation/subscribeToTopic.yml"
        template_parameters:
          EnvironmentTag: "{{environment_tag}}"
          EnvironmentType: "{{environment_type}}"
          Region: "eu-west-1"
          ConceptTopicARN: "{{SNSConceptTopicARN}}"
          SecondaryQueueARN: "{{SQSSecondaryConceptARN}}"
        tags:
          environment: "{{environment_type}}"
          systemCode: "upp"
          teamDL: "universal.publishing.platform@ft.com"
          description: "Concept Publishing Secondary Queues Stack - {{environment_tag}}"
      register: subscription_stack_output

    - debug:
        msg: "{{subscription_stack_output}}"
