---
- name: Decomm Fluentd Kinesis

  vars:
    cloudformation_stack: "annotations-monitoring-{{ cluster }}"

  tasks:
  - name: Decommission annotations monitoring kinesis analytics application
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      region: "{{ aws_region }}"
      stack_name: "{{ cloudformation_stack }}"
      state: "absent"
