version: 2
jobs:
  upp-elasticsearch-provisioner:
    docker:
      - image: docker:stable-git
    environment:
      - PROVISIONER_NAME: "upp-elasticsearch-provisioner"
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - upp-elasticsearch-provisioner-{{ .Branch }}
          paths:
            - /caches/upp-elasticsearch-provisioner.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/$PROVISIONER_NAME.tar | true
      - run:
          name: Set Docker image tag based on branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] ; then
              echo 'export DOCKER_TAG=latest' >> $BASH_ENV
            else
              echo 'export DOCKER_TAG=${CIRCLE_BRANCH}' >> $BASH_ENV
            fi
      - run:
          name: Build Docker image
          command: |
            source $BASH_ENV
            docker build --cache-from=coco/$PROVISIONER_NAME:$DOCKER_TAG -t coco/$PROVISIONER_NAME:$DOCKER_TAG $PROVISIONER_NAME/
      - run:
          name: Save Docker image layer cache
          command: |
            source $BASH_ENV
            mkdir -p /caches
            docker save -o /caches/$PROVISIONER_NAME.tar coco/$PROVISIONER_NAME:$DOCKER_TAG
      - save_cache:
          key: upp-elasticsearch-provisioner-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/upp-elasticsearch-provisioner.tar
      - deploy:
          name: Push Docker image
          command: |
            source $BASH_ENV
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push coco/$PROVISIONER_NAME:$DOCKER_TAG
workflows:
  version: 2
  build:
    jobs:
      - upp-elasticsearch-provisioner
