version: 2
jobs:
  upp-elasticsearch-provisioner:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - {{ .Environment.CIRCLE_JOB }}-{{ .Branch }}
          paths:
            - /caches/{{ .Environment.CIRCLE_JOB }}.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/${CIRCLE_JOB}.tar | true
      - run:
          name: Set Docker image tag based on branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] ; then
              echo 'export DOCKER_TAG=latest' >> $BASH_ENV
            else
              echo 'export DOCKER_TAG=${CIRCLE_BRANCH}' >> $BASH_ENV
            fi
      - run:
          name: Build Docker image
          command: |
            source ${BASH_ENV}
            docker build --cache-from=coco/${CIRCLE_JOB}:${DOCKER_TAG} -t coco/${CIRCLE_JOB}:${DOCKER_TAG} ${CIRCLE_JOB}/
      - run:
          name: Save Docker image layer cache
          command: |
            source ${BASH_ENV}
            mkdir -p /caches
            docker save -o /caches/${CIRCLE_JOB}.tar coco/${CIRCLE_JOB}:${DOCKER_TAG}
      - save_cache:
          key: {{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/{{ .Environment.CIRCLE_JOB }}.tar
      - deploy:
          name: Push Docker image
          command: |
            source ${BASH_ENV}
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker push coco/${CIRCLE_JOB}:${DOCKER_TAG}
workflows:
  version: 2
  build:
    jobs:
      - upp-elasticsearch-provisioner
