version: 2
jobs:
  upp-concept-publishing-provisioner:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t coco/upp-concept-publishing-provisioner:latest upp-concept-publishing-provisioner/
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push coco/upp-concept-publishing-provisioner:latest
  upp-delivery-provisioner:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t coco/upp-delivery-provisioner:latest upp-delivery-provisioner/
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push coco/upp-delivery-provisioner:latest
  upp-elasticsearch-provisioner:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          if [ ${CIRCLE_BRANCH} == 'master' ] ; then
            export DOCKER_TAG='latest'
          else
            export DOCKER_TAG=${CIRCLE_BRANCH}
          fi
          docker build -t coco/upp-elasticsearch-provisioner:latest upp-elasticsearch-provisioner/
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push coco/upp-elasticsearch-provisioner:$DOCKER_TAG
  upp-neo4j-provisioner:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t coco/upp-neo4j-provisioner:latest upp-neo4j-provisioner/
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push coco/upp-neo4j-provisioner:latest
  upp-pub-provisioner:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t coco/upp-pub-provisioner:latest upp-pub-provisioner/
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push coco/upp-pub-provisioner:latest
  upp-rds-provisioner:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t coco/upp-rds-provisioner:latest upp-rds-provisioner/
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push coco/upp-rds-provisioner:latest
workflows:
  version: 2
  build:
    jobs:
      - upp-delivery-provisioner
      - upp-concept-publishing-provisioner
      - upp-elasticsearch-provisioner
      - upp-neo4j-provisioner
      - upp-pub-provisioner
      - upp-rds-provisioner
