---
- name: Decommission stack
  hosts: localhost
  connection: local

  vars_files:
  - vault_{{ aws_account }}.yml

  tasks:
  - name: Remove Factset Ec2 Instance stack
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "upp-factset-loader-{{ environment_name }}"
      region: eu-west-1
      state: "absent"

  - name: Remove Factset Rds stack
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "upp-factset-rds-{{ environment_name }}"
      region: eu-west-1
      state: "absent"

  - name: Remove Factset RDS Security Group
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "upp-factset-rds-security-group-{{ environment_name }}"
      region: eu-west-1
      state: "absent"

  - name: Remove Factset Ec2 Security Group stack
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "upp-factset-loader-security-group-{{ environment_name }}"
      region: eu-west-1
      state: "absent"
