---
- name: provision stack
  hosts: localhost
  connection: local

  vars_files:
    - vault_{{ aws_account }}.yml

  tasks:
  - name: Launch Factset Loader Security Group stack
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "upp-factset-loader-security-group-{{ environment_name }}"
      state: present
      region: eu-west-1
      disable_rollback: true
      template: /cloudformation/loader-security-group-provisioner.yml
      template_parameters:
        DBVPC: "{{ vpc_id }}"
        EnvironmentName: "{{ environment_name }}"
        EnvironmentTag: "{{ environment_tag }}"
    register: loader_security_group_output

  - name: Save loader security group stack output as variable
    set_fact:
      LoaderSecurityGroupId: "{{loader_security_group_output.stack_outputs.LoaderSecurityGroupId}}"


  - name: Launch Factset Loader Ec2 stack
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "upp-factset-loader-{{ environment_name }}"
      state: present
      region: eu-west-1
      disable_rollback: true
      template: /cloudformation/ec2-loader-provisioner.yml
      template_parameters:
        DBSubnetIds: "{{ subnet_ids }}"
        Ec2InstanceType: "m5.large"
        EnvironmentName: "{{ environment_name }}"
        EnvironmentTag: "{{ environment_tag }}"
        LoaderSecurityGroup: "{{ LoaderSecurityGroupId }}"
        FTResourcesSecurityGroup: "{{ FTResourcesSecurityGroupId }}"
    tags:
      - loader

  - name: Launch Factset Security and Parameter Group stack
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "upp-factset-rds-security-group-{{ environment_name }}"
      state: present
      region: eu-west-1
      disable_rollback: true
      template: /cloudformation/security-and-parameter-group-provisioner.yml
      template_parameters:
        DBVPC: "{{ vpc_id }}"
        EnvironmentName: "{{ environment_name }}"
        EnvironmentTag: "{{ environment_tag }}"
        LoaderSecurityGroup: "{{ LoaderSecurityGroupId }}"
    register: group_stack_output

  - name: Save group outputs as variable
    set_fact:
      FactsetSecurityGroupId: "{{group_stack_output.stack_outputs.FactsetSecurityGroupId}}"
      FactsetParameterGroupName: "{{group_stack_output.stack_outputs.FactsetParameterGroupName}}"

  - name: Launch Factset RDS stack
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "upp-factset-rds-{{ environment_name }}"
      state: present
      region: eu-west-1
      disable_rollback: true
      template: /cloudformation/rds-provisioner.yml
      template_parameters:
        DBSubnetIds: "{{ subnet_ids }}"
        DBInstanceType: db.r4.large
        DBInstanceMasterUsername: admin
        DBInstanceMasterPassword: "{{ db_master_password }}"
        EnvironmentName: "{{ environment_name }}"
        EnvironmentTag: "{{ environment_tag }}"
        DBSecurityGroup: "{{ FactsetSecurityGroupId }}"
        DBParameterGroup: "{{ FactsetParameterGroupName }}"
