Description: "Creates primary concept notification stream for concept updates in UPP"

Parameters:
  EnvironmentTag:
    Type: String
    Default: "dev"
  EnvironmentType:
    Type: String
    Default: "d"
  Region:
    Type: String
    Default: "eu-west-1"

Resources:
  ConceptNotificationStream:
    Type: "AWS::Kinesis::Stream"
    Properties:
      Name: !Join [ "", ["upp-primary-concept-notifications-", !Ref EnvironmentTag]]
      RetentionPeriodHours: 24
      ShardCount: 1
      Tags:
        - Key: "systemCode"
          Value: "upp"
        - Key: "teamDL"
          Value: "universal.publishing@ft.com"
        - Key: "environment"
          Value: !Ref EnvironmentType
        - Key: "description"
          Value: !Join ["", ["Primary Concept Notification Stream - ", !Ref EnvironmentTag]]
