Description: "Creates an s3 bucket and a dynamoDB table for publishing of concepts in UPP."

Parameters:
  EnvironmentTag:
    Type: String
    Default: "dev"
  EnvironmentType:
    Type: String
    Default: "d"
  Region:
    Type: String
    Default: "eu-west-1"
  SNSTopicARN:
    Type: String
    Default: "ARN of the primary SNS topic"

Resources:
  # Create the S3 bucket with the notifications.
  S3ConceptPublish:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join [ "", ["upp-concept-normalised-store-", !Ref EnvironmentTag]]
      AccessControl: Private
      NotificationConfiguration:
        TopicConfigurations:
          - Event: "s3:ObjectCreated:*"
            Topic: !Ref SNSTopicARN
