Description: "Creates SQS Queue and kinesis stream in secondary region for publishing of concepts in UPP."

Parameters:
  EnvironmentTag:
    Type: String
    Default: "pre-prod"
  EnvironmentType:
    Type: String
    Default: "t"
  Region:
    Type: String
    Default: "Secondary region"
  SNSTopicARN:
    Type: String
    Default: "ARN of the primary SNS topic"
  SQSConceptQueueMaxDepth:
    Type: Number
    Default: 50000

Resources:
  # Create another SQS queue if multi-region is set to true.
  SNSDeadLetterQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Join ["", ["upp-concept-publish-dead-letter-", !Ref EnvironmentTag, "-2"]]

  SQSQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Join ["", ["upp-concept-publish-notifications-", !Ref EnvironmentTag, "-2"]]
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SNSDeadLetterQueue.Arn
        maxReceiveCount: 5

  SQSConceptQueueOverflowAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ["", ["Triggered when SQS concept queue alarms"]]

  SQSConceptQueueOverflowAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Join ["", ["upp-concept-publish-notifications-alarm-", !Ref EnvironmentTag, "-2"]]
      AlarmDescription: !Join ["", ["Alarm if queue depth grows beyond ", !Ref SQSConceptQueueMaxDepth, " messages"]]
      Namespace: "AWS/SQS"
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value : { "Fn::GetAtt" : [ "SQSQueue", "QueueName"] }
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Ref SQSConceptQueueMaxDepth
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - Ref: SQSConceptQueueOverflowAlarmTopic
      InsufficientDataActions:
        - Ref: SQSConceptQueueOverflowAlarmTopic

  SQSConceptQueueOverflowAlarmSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: p2o5v3s3i6a7x0q7@financialtimes.slack.com #upp-concept-load-err channel on Slack
      Protocol: email
      TopicArn: !Ref SQSConceptQueueOverflowAlarmTopic

  SQSQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - !Ref SQSQueue
      PolicyDocument:
        Version: "2012-10-17"
        Id: ConceptNotificationQueuePolicy
        Statement:
          -
            Sid: "subscribe-to-primary-sns-queue"
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "SQS:SendMessage"
            Resource: !GetAtt SQSQueue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": !Ref SNSTopicARN
          -
            Sid: "communicate-with-sqs"
            Effect: "Allow"
            Principal:
              AWS: !Join ["", ["arn:aws:iam::", !Ref 'AWS::AccountId', ":user/content-containers-apps"]]
            Action: "SQS:*"
            Resource: !GetAtt SQSQueue.Arn

Outputs:
  SecondaryConceptARN:
    Description: Secondary regions SQS ARN
    Value: !GetAtt SQSQueue.Arn
