Description: "Creates SQS Queue and kinesis stream in secondary region for publishing of concepts in UPP."

Parameters:
  EnvironmentTag:
    Type: String
    Default: "pre-prod"
  EnvironmentType:
    Type: String
    Default: "t"
  Region:
    Type: String
    Default: "Secondary region"
  SNSTopicARN:
    Type: String
    Default: "ARN of the primary SNS topic"

Resources:
  # Create another SQS queue if multi-region is set to true.
  SNSDeadLetterQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Join ["", ["upp-concept-publish-dead-letter-", !Ref EnvironmentTag, "-2"]]

  SQSQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Join ["", ["upp-concept-publish-notifications-", !Ref EnvironmentTag, "-2"]]
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SNSDeadLetterQueue.Arn
        maxReceiveCount: 5

  SQSQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - !Ref SQSQueue
      PolicyDocument:
        Version: "2012-10-17"
        Id: ConceptNotificationQueuePolicy
        Statement:
          -
            Sid: "subscribe-to-primary-sns-queue"
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "SQS:SendMessage"
            Resource: !GetAtt SQSQueue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": !Ref SNSTopicARN
          -
            Sid: "communicate-with-sqs"
            Effect: "Allow"
            Principal:
              AWS: !Join ["", ["arn:aws:iam::", !Ref 'AWS::AccountId', ":user/content-containers-apps"]]
            Action: "SQS:*"
            Resource: !GetAtt SQSQueue.Arn

Outputs:
  SecondaryConceptARN:
    Description: Secondary regions SQS ARN
    Value: !GetAtt SQSQueue.Arn
