#cloud-config
write_files:
  - path: /tmp/ft-env-variables
    permissions: "0644"
    owner: "root"
    content: |
      environment_tag={{environment_tag}}
      persistent_tag={{persistent_tag}}
      token={{token}}

coreos:
  units:
    - name: authorized_keys.service
      command: start
      content: |
        [Unit]
        Description=Update authorized_keys

        [Service]
        Type=oneshot
        ExecStartPre=/bin/sh -c "mkdir -p /home/core/.ssh && touch /home/core/.ssh/authorized_keys"
        ExecStart=/bin/sh -c "curl -sSL --retry 5 --retry-delay 2 -o /tmp/authorized_keys.sha512 https://raw.githubusercontent.com/Financial-Times/up-ssh-keys/master/authorized_keys.sha512"
        ExecStart=/bin/sh -c "curl -sSL --retry 5 --retry-delay 2 -o /tmp/authorized_keys https://raw.githubusercontent.com/Financial-Times/up-ssh-keys/master/authorized_keys"
        ExecStart=/bin/sh -c "cd /tmp/ && sha512sum -c authorized_keys.sha512 && cp authorized_keys /home/core/.ssh/authorized_keys && chmod 700 /home/core/.ssh && chmod 600 /home/core/.ssh/authorized_keys && chown -R core:core /home/core/.ssh"
    - name: bypass-user-data-limit.service
      command: start
      content: |
        [Unit]
        Description=Update the machine using our own cloud config, due to 16kb size limit on AWS user data

        [Service]
        EnvironmentFile=/etc/environment
        ExecStartPre=/usr/bin/wget -qO /tmp/substitute-ft-env-variables.sh https://raw.githubusercontent.com/Financial-Times/upp-provisioners/{{branch_name}}/upp-delivery-provisioner/sh/substitute-ft-env-variables.sh
        ExecStartPre=/usr/bin/wget -qO /tmp/instance_user_data.yaml https://raw.githubusercontent.com/Financial-Times/upp-provisioners/{{branch_name}}/upp-delivery-provisioner/ansible/userdata/persistent_instance_user_data.yaml
        ExecStartPre=/usr/bin/chmod +x /tmp/substitute-ft-env-variables.sh
        ExecStartPre=/tmp/substitute-ft-env-variables.sh
        ExecStart=/usr/bin/coreos-cloudinit --from-file /tmp/instance_user_data.yaml
        # ExecStartPost=/usr/bin/rm /tmp/ft-env-variables /tmp/substitute-ft-env-variables.sh /tmp/instance_user_data.yaml
        RemainAfterExit=yes
        Type=oneshot
