# Published base URL of the web service.
# Required if using DNS, Load Balancer, or http->https redirections.
BASE_URL: https://upp-coreupdate.in.ft.com

# (required) Unique secret session string.
# You can generate a UUID from the command line using the `uuidgen` command
SESSION_SECRET: "A4B324FA-5560-487C-98E7-90287F7ECA2B"

# Set this to 'false' if using Google authentication.
DISABLE_AUTH: false

# Enables Google OAuth, otherwise set DISABLE_AUTH to 'true'
# Configure at https://console.developers.google.com
GOOGLE_OAUTH_CLIENT_ID: example.apps.googleusercontent.com 
GOOGLE_OAUTH_CLIENT_SECRET: example 
# The redirect URL follows this format, substituting the BASE_URL: http://localhost:8000/admin/v1/oauth/login
GOOGLE_OAUTH_REDIRECT_URL: https://upp-coreupdate.in.ft.com/admin/v1/oauth/login

# Address and port to listen on.
LISTEN_ADDRESS: ":8000"

# Postgres database settings.
# Format: postgres://username:password@host:port/database-name
DB_URL: "postgres://coreos:supersecretpassword@localhost:5432/coreupdate?sslmode=disable"
DBTIMEOUT: 0
DBMAXIDLE: 0
DBMAXACTIVE: 100

# (Optional) sets a path to enable CoreUpdate's static package serving feature.
# Comment out to disable.
#STATIC_PACKAGES_DIR: /packages

# (Optional) enables uploading of package payloads to the server.
#ENABLE_PACKAGE_UPLOADS: true

# (Optional) Enable if syncing with upstream CoreUpdate instances.
# Zero value is disabled.
# This should be disabled if you plan to synchronize packages manually.
UPSTREAM_SYNC_INTERVAL: 10

# (Optional) enables TLS
#TLS_CERT_FILE:
#TLS_KEY_FILE:

