#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

apt-get update -y
apt-get install -y python3-pip python3-dev
rm -rf /var/lib/apt/lists/*
cd /usr/local/bin
ln -s /usr/bin/python3 python
pip3 install --upgrade pip
