---
- name: Decommission stack
  hosts: localhost
  connection: local

  vars:
    cluster_name: "pac-aurora-{{ cluster }}"

  vars_files:
    - vaults/vault_{{ environment_type }}.yml

  tasks:
  - name: Promote EU DB Cluster # this step ensures that we can decom the cluster regardless of whether it is the Master db or not.
    script: tasks/promote_read_replica.sh
    environment:
      AWS_REGION: "eu-west-1"
      AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    ignore_errors: yes

  - name: Remove Aurora in EU
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "{{ cluster_name }}"
      region: "eu-west-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Parameter groups in EU
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "{{ cluster_name }}-db-group"
      region: "eu-west-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Aurora subnet in EU
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "{{ cluster_name }}-db-subnet"
      region: "eu-west-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Cloudwatch alarms in EU
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "{{ cluster_name }}-alarms"
      region: "eu-west-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Aurora replica in US
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "{{ cluster_name }}"
      region: "us-east-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Aurora subnet in US
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "{{ cluster_name }}-db-subnet"
      region: "us-east-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Parameter groups in US
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "{{ cluster_name }}-db-group"
      region: "us-east-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Cloudwatch alarms in US
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "{{ cluster_name }}-alarms"
      region: "us-east-1"
      state: "absent"
    ignore_errors: yes

  - name: Message
    debug:
      msg: "Manually delete the Route53 records: {{ cluster }}-eu-rds-pac, {{ cluster }}-us-rds-pac and {{ cluster }}-rds-pac"
