---
- name: Decommission stack
  hosts: localhost
  connection: local

  vars:
    cluster_name: "pac-aurora-{{ cluster }}"

  vars_files:
    - vaults/vault_{{ environment_type }}.yml

  tasks:
  - name: Remove Aurora in EU
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-eu"
      region: "eu-west-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Parameter groups in EU
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-eu-db-group"
      region: "eu-west-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Aurora subnet in EU
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-eu-db-subnet"
      region: "eu-west-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Aurora replica in US
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-us"
      region: "us-east-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Aurora subnet in US
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-us-db-subnet"
      region: "us-east-1"
      state: "absent"
    ignore_errors: yes

  - name: Remove Parameter groups in US
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-us-db-group"
      region: "us-east-1"
      state: "absent"
    ignore_errors: yes

  - include: tasks/delete_cname.yml
    vars:
      dns_cname: "{{ cluster }}-eu-rds-pac"

  - include: tasks/delete_cname.yml
    vars:
      dns_cname: "{{ cluster }}-us-rds-pac"
