---
- name: provision stack
  hosts: localhost
  connection: local

  vars:
    cluster_name: "pac-aurora-{{ cluster }}"

  vars_files:
  - vault_{{ environment_type }}.yml

  tasks:
  - name: Log vars
    debug:
      msg: "cluster_name: '{{ cluster_name }}'"

  - name: Retrieve EU DB Cluster ARN
    script: /usr/local/bin/arn.sh us-east-1
    register: aurora_us_arn

  - name: Promote
    rds:
      command: promote
      instance_name:
