---
- name: Failover
  hosts: localhost
  connection: local

  vars:
    cluster_name: "pac-aurora-{{ cluster }}"

  vars_files:
    - vaults/vault_{{ environment_type }}.yml
    - vars/{{ aws_account }}.yml

  tasks:
  - name: Log vars
    debug:
      msg: "Failing over cluster_name: '{{ cluster_name }}' from region '{{ failover_from_region }}' to region '{{ failover_to_region }}'"

  - name: "Update CNAME for Aurora {{ cluster }}-rds-pac -> {{ cluster }}-{{ regions[failover_to_region].shortname }}-rds-pac.upp.ft.com"
    script: tasks/manage-cname.bash UPSERT
    environment:
      DNS_CNAME: "{{ cluster }}-rds-pac"
      DB_HOSTNAME: "{{ cluster }}-{{ regions[failover_to_region].shortname }}-rds-pac.upp.ft.com"

  - name: Promote DB Cluster
    script: tasks/promote_read_replica.sh
    environment:
      AWS_REGION: "{{ failover_to_region }}"
      AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    register: promote_output
    ignore_errors: yes

  - name: Log promote output
    debug:
      msg: "{{ promote_output }}"

  - name: Remove Cloudwatch alarms
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "{{ cluster_name }}-alarms"
      region: "{{ failover_from_region }}"
      state: "absent"
    ignore_errors: yes
