---
- name: provision stack
  hosts: localhost
  connection: local

  vars:
    cluster_name: "pac-aurora-{{ cluster }}"

  vars_files:
    - vaults/vault_{{ environment_type }}.yml
    - vars/{{ aws_account }}.yml

  tasks:
  - name: Log vars
    debug:
      msg: "cluster_name: '{{ cluster_name }}'"

  - name: Add DB Parameter Groups to eu-west-1
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-eu-db-group"
      state: present
      region: "eu-west-1"
      disable_rollback: true
      template: /cloudformation/aurora-db-parameter-groups.yml
      template_parameters:
        EnvironmentName: "{{ cluster_name }}"
        TagEnvironment: "{{ environment_type }}"
    register: db_param_group_eu

  - name: Add DB Parameter Groups to us-east-1
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-us-db-group"
      state: present
      region: "us-east-1"
      disable_rollback: true
      template: /cloudformation/aurora-db-parameter-groups.yml
      template_parameters:
        EnvironmentName: "{{ cluster_name }}"
        TagEnvironment: "{{ environment_type }}"
    register: db_param_group_us

  - name: Add DB Subnet to eu-west-1
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-eu-db-subnet"
      state: present
      region: "eu-west-1"
      disable_rollback: true
      template: /cloudformation/aurora-pac-subnet.yml
      template_parameters:
        EnvironmentName: "{{ cluster_name }}"
        TagEnvironment: "{{ environment_type }}"
        DBSubnetIds: "{{ eu_subnets }}"
    register: db_subnet_eu

  - name: Launch Aurora DB Cloudformation stack in eu-west-1
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-eu"
      state: present
      region: "eu-west-1"
      disable_rollback: true
      template: /cloudformation/aurora-pac-eu.yml
      template_parameters:
        EnvironmentName: "{{ cluster_name }}"
        DBVPC: "{{ eu_vpc }}"
        DBSubnetGroup: "{{ db_subnet_eu.stack_outputs.DBSubnetGroup }}"
        DBSecurityGroups: "{{ eu_security_groups }}"
        DBParameterGroup: "{{ db_param_group_eu.stack_outputs.DBParameterGroup }}"
        DBClusterParameterGroup: "{{ db_param_group_eu.stack_outputs.DBClusterParameterGroup }}"
        DBInstanceType: db.t2.small
        DBInstanceMasterUsername: AdminUser
        DBInstanceMasterPassword: "{{ db_master_password }}"
        DBInstanceDBName: pac
        TagEnvironment: "{{ environment_type }}"
    register: aurora_eu_stack

  - include: tasks/create_cname.yml
    vars:
      dns_cname: "{{ cluster }}-eu-rds-pac"
      hostname: "{{ aurora_eu_stack.stack_outputs.DBHostname }}"

  - name: Retrieve EU DB Cluster ARN
    script: /usr/local/bin/arn.sh
    environment:
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    register: aurora_eu_arn

  - name: EU Cluster ARN
    debug:
      msg: "EU ARN: '{{ aurora_eu_arn.stdout }}'"

  - name: Add DB Subnet to us-east-1
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-us-db-subnet"
      state: present
      region: "us-east-1"
      disable_rollback: true
      template: /cloudformation/aurora-pac-subnet.yml
      template_parameters:
        EnvironmentName: "{{ cluster_name }}"
        TagEnvironment: "{{ environment_type }}"
        DBSubnetIds: "{{ us_subnets }}"
    register: db_subnet_us

  - name: Launch Replica Aurora DB Cloudformation stack in us-east-1
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ cluster_name }}-us"
      state: present
      region: "us-east-1"
      disable_rollback: true
      template: /cloudformation/aurora-pac-replica.yml
      template_parameters:
        EnvironmentName: "{{ cluster_name }}"
        DBVPC: "{{ us_vpc }}"
        DBSecurityGroups: "{{ us_security_groups }}"
        DBParameterGroup: "{{ db_param_group_us.stack_outputs.DBParameterGroup }}"
        DBClusterParameterGroup: "{{ db_param_group_us.stack_outputs.DBClusterParameterGroup }}"
        DBSubnetGroup: "{{ db_subnet_us.stack_outputs.DBSubnetGroup }}"
        DBInstanceType: db.t2.small
        DBInstanceMasterUsername: AdminUser
        DBInstanceMasterPassword: "{{ db_master_password }}"
        DBInstanceDBName: pac
        ReplicationSourceIdentifier: "{{ aurora_eu_arn.stdout }}"
        TagEnvironment: "{{ environment_type }}"
    register: aurora_us_stack

  - include: tasks/create_cname.yml
    vars:
      dns_cname: "{{ cluster }}-us-rds-pac"
      hostname: "{{ aurora_us_stack.stack_outputs.DBHostname }}"

  - include: tasks/create_cname.yml
    vars:
      dns_cname: "{{ cluster }}-rds-pac"
      hostname: "{{ cluster }}-eu-rds-pac.ft.com"
