- hosts: all

  vars:
    aws_default_region: "eu-west-1"

  tasks:
    - name: Create Jenkins CloudFormation stack
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        stack_name: "{{instance_name}}"
        state: "present"
        region: "{{aws_default_region}}"
        template: "/cloudformation/jenkins.yml"
        template_parameters:
          InstanceName: "{{instance_name}}"
          EnvironmentType: "{{environment_type}}"
        tags:
          Name: "{{instance_name}}"
          environment: "{{environment_type}}"
          teamDL: "universal.publishing.platform@ft.com"
          systemCode: "upp"
      register: cf_stack_output

    - debug:
        msg: "{{cf_stack_output}}"

    - name: Save ALB DNS as a variable
      set_fact:
        alb_dns: "{{cf_stack_output.stack_outputs.JenkinsALBDNS}}"

    - name: Create or update Jenkins CNAME
      include: tasks/create_update_cname.yml
