- hosts: all

  vars_files:
    - vault_{{ aws_account }}.yml

  tasks:
    - name: Create Queues for Concept Events Pipeline Stack
      cloudformation:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        stack_name: "upp-concept-events-sqs-{{environment_name}}"
        state: "present"
        region: "{{aws_default_region}}"
        template: "/cloudformation/sqs-single-region.yml"
        template_parameters:
          EnvironmentName: "{{ environment_name }}"
          EnvironmentTag: "{{ environment_tag }}"
        tags:
          environment: "{{environment_tag}}"
          systemCode: "upp"
          teamDL: "universal.publishing.platform@ft.com"
          description: "Concept Events Pipeline Queues Stack - {{environment_name}}"
      register: concept_pub_stack_output

    - debug:
        msg: "{{concept_pub_stack_output}}"

    - name: Launch Concept Events Parameter Group stack
      cloudformation:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        stack_name: "upp-concept-events-rds-parameter-group-{{ environment_name }}"
        state: present
        region: eu-west-1
        disable_rollback: true
        template: /cloudformation/parameter-group-provisioner.yml
        template_parameters:
          EnvironmentName: "{{ environment_name }}"
          EnvironmentTag: "{{ environment_tag }}"
      register: group_stack_output

    - name: Save group outputs as variable
      set_fact:
        ConceptEventsParameterGroupName: "{{group_stack_output.stack_outputs.ConceptEventsParameterGroupName}}"

    - name: Launch Concept Events RDS stack
      cloudformation:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        stack_name: "upp-concept-events-rds-{{ environment_name }}"
        state: present
        region: eu-west-1
        disable_rollback: true
        template: /cloudformation/rds-provisioner.yml
        template_parameters:
          DBSubnetIds: "{{ subnet_ids }}"
          DBInstanceType: db.r4.large
          DBInstanceMasterUsername: admin
          DBInstanceMasterPassword: "{{ db_master_password }}"
          EnvironmentName: "{{ environment_name }}"
          EnvironmentTag: "{{ environment_tag }}"
          DBSecurityGroup: "{{ security_group_id }}"
          DBParameterGroup: "{{ ConceptEventsParameterGroupName }}"
