#!/bin/sh

echo "Running load..."

aws s3 cp s3://com.ft.coco-factset-data/2017-03-07/ppl_people_v1_full_1220.txt ppl_people.txt

sed -i -e "s|{{CONN}}|${PG_CONNECTION}|g" ppl_people_load

pgloader ppl_people_load

