#!/bin/sh
set -x
set -e
start=$SECONDS
echo "Running load..."

aws s3 ls  s3://com.ft.coco-factset-data/2017-03-08/

aws s3 cp s3://com.ft.coco-factset-data/2017-03-08/2017-03-08.zip .

ls -la

mv *.zip data.zip

pgloader ppl_people_load

pgloader ent_entity_load

duration=$(( SECONDS - start ))
echo "Duration was $duration"
