#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

cd /tmp

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install --update

rm awscliv2.zip
rm -rf ./aws/
