- hosts: 127.0.0.1
  connection: local

  vars:
    region: eu-west-1
  vars_files:
    - keys.yaml

  tasks:
    - name: Terminate instances
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        state: absent
        instance_ids: "{{instanceIds}}"

    - name: Delete DNS tunnel record
      ignore_errors: yes
      uri:
        url: "https://dns-api.in.ft.com/v2/"
        method: DELETE
        HEADER_x-api-key: "{{konstructor_api_key}}"
        body:
          zone: "ft.com"
          name: "{{environment_tag}}-tunnel-up"
        emailAddress: "universal.publishing.platform@ft.com"
        body_format: json

    - name: Delete DNS ELB record
      ignore_errors: yes
      uri:
        url: "https://dns-api.in.ft.com/v2/"
        method: DELETE
        HEADER_x-api-key: "{{konstructor_api_key}}"
        body:
          zone: "ft.com"
          name: "{{environment_tag}}-up"
          emailAddress: "universal.publishing.platform@ft.com"
        body_format: json

    - name: Wait 120s for instances to be terminated and release enis
      shell: "sleep 120"

    - name: Delete cluster-elb
      ec2_elb_lb:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        name: "coreos-up-{{clusterid}}"
        state: absent

    - name: Wait 120s for elb to be terminated and release enis
      shell: "sleep 120"

    - name: Delete fleet security group
      ec2_group:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        name: "coreos-up-{{clusterid}}"
        description: Fleet security group
        state: absent
