AWSTemplateFormatVersion: 2010-09-09
Description: >
  Template to spin-up an OpenSearch cluster that contains FT content used by CCF platform

Parameters:
  EnvironmentTag:
    Description: Environment type (Dev,Test or Production).
    Type: String
    AllowedValues:
      - 'd'
      - 't'
      - 'p'
    Default: 'd'

  TeamDLTag:
    Description: Tag of the TeamDL
    Type: String
    AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
    ConstraintDescription: There must be a valid email address for the TeamDL
    Default: 'universal.publishing.platform@ft.com'

  SystemCodeTag:
    Description: The system code for the environment
    Type: String
    Default: 'upp'

  ClusterName:
    Description: The name of the ES cluster
    Type: String

  BackupRole:
    Description: The IAM role used for accessing the S3 bucket when creating ES snapshots
    Type: String
    Default: 'upp-elasticsearch-backup-role'

  BackupBucketName:
    Description: The name of the S3 bucket used for ES snapshot backups
    Type: String

Resources:

  BackupBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: BackupBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "s3:*"
          Resource:
            - !Join [ "", [ !GetAtt BackupBucket.Arn, "/*" ] ]
            - !GetAtt BackupBucket.Arn
          Principal:
            AWS: !Join [ "", [ "arn:aws:iam::", !Ref 'AWS::AccountId', ":role/", !Ref 'BackupRole' ] ]

  BackupBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BackupBucketName
      Tags:
        - Key: environment
          Value: !Ref EnvironmentTag
        - Key: teamDL
          Value: !Ref TeamDLTag
        - Key: systemCode
          Value: !Ref SystemCodeTag
        - Key: description
          Value: !Ref ClusterName

  OpenSearchDomain:
    Type: "AWS::OpenSearchService::Domain"
    Properties:
      DomainName: !Ref ClusterName
      EngineVersion: "OpenSearch_1.3"
      ClusterConfig:
        InstanceCount: "3"
        InstanceType: "m5.xlarge.search"
        DedicatedMasterEnabled: "true"
        DedicatedMasterType: "m5.large.search"
        DedicatedMasterCount: "3"
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 50
        VolumeType: "gp2"
      SnapshotOptions:
        AutomatedSnapshotStartHour: "0"
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: "true"
      Tags:
        - Key: environment
          Value: !Ref EnvironmentTag
        - Key: teamDL
          Value: !Ref TeamDLTag
        - Key: systemCode
          Value: !Ref SystemCodeTag
        - Key: description
          Value: !Ref ClusterName
