---
- name: Delete stack
  hosts: localhost
  connection: local

  tasks:
  - name: Delete Jumpbox
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      stack_name: "upp-jumpbox-{{ aws_region }}"
      state: absent
