AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Jenkins Controller Template

Parameters:
  stackResourcesPrefix:
    Type: String
    Description: "Stack resources prefix"
    Default: "upp"

  jenkinsUid:
    Type: String
    Description: "Set unique ID"

  jenkinsControllerInstanceType:
    Description: "Type of EC2 instance to launch for the server. Only Compute type nodes are currently specified."
    Type: String

  stackVpcId:
    Description: "VPC ID that this stack will be launched in."
    Type: AWS::EC2::VPC::Id
    AllowedPattern: "[a-z0-9-]*"

  jenkinsControllerSubnetId:
    Description: "VPC Subnet that Jenkins will be launched in."
    Type: AWS::EC2::Subnet::Id
    AllowedPattern: "[a-z0-9-]*"

  jenkinsControllerKeyPairName:
    Description: "Name of an existing EC2 KeyPair to enable SSH access to the instance(s)."
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair

  jenkinsControllerImageId:
    Description: "The ID of the AMI"
    Type: String

  jenkinsControllerAz:
    Description: "The Availability Zone of the instance"
    Type: String

  stackSecurityGroupIds:
    Description: "The IDs of the security groups"
    Type: "List<AWS::EC2::SecurityGroup::Id>"

  jenkinsControllerEbsDeviceName:
    Description: "The device name (for example, /dev/sdh or xvdh)"
    Type: String
    Default: /dev/xvdj

  jenkinsControllerEbsId:
    Description: "A volume to attach to the instance."
    Type: String

  jenkinsControllerJavaOptions:
    Type: String
    Default: "-Djava.awt.headless=true"

  albListenerCertificateArn:
    Description: "The ARN of the certificate"
    Type: String

  jenkinsAlbSubnets:
    Description: "ALB subnets"
    Type: "List<AWS::EC2::Subnet::Id>"

  environmentTag:
    Description: "The environment tag"
    Type: String

  systemCodeTag:
    Description: "The systemCode tag"
    Type: String
    Default: "upp"

  teamDlTag:
    Description: "The teamDL tag"
    Type: String
    Default: "universal.publishing.platform@ft.com"


Resources:
  JenkinsController:
    Description: "Jenkins Controller instance"
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref jenkinsControllerImageId
      InstanceType: !Ref jenkinsControllerInstanceType
      AvailabilityZone: !Ref jenkinsControllerAz
      SubnetId: !Ref jenkinsControllerSubnetId
      SecurityGroupIds: !Ref stackSecurityGroupIds
      IamInstanceProfile: "FT-EC2-Role"
      KeyName: !Ref jenkinsControllerKeyPairName
      Volumes:
        - Device: !Ref jenkinsControllerEbsDeviceName
          VolumeId: !Ref jenkinsControllerEbsId
      UserData:
        Fn::Base64: !Sub |
          #!/usr/bin/env bash

          set -euox pipefail

          sed -i 's/__JENKINS_JAVA_OPTIONS__/${jenkinsControllerJavaOptions}/' /etc/sysconfig/jenkins

          echo ${jenkinsControllerEbsDeviceName} /var/lib/jenkins ext4 defaults,nofail 0 2 >> /etc/fstab
          mount ${jenkinsControllerEbsDeviceName} /var/lib/jenkins
          chown jenkins:jenkins /var/lib/jenkins

          systemctl start docker
          systemctl start jenkins

          ### Install amazon-ftbase-v2
          /usr/bin/aws s3 cp s3://amazon-ftbase/amazon-ftbase2/releases/bootstrap.sh /
          bash /bootstrap.sh -s eng -e ${environmentTag} --disable-yum-security-update-schedule
      Tags:
        - Key: "Name"
          Value: !Sub ${stackResourcesPrefix}-jenkins-${jenkinsUid}
        - Key: "systemCode"
          Value: !Sub ${systemCodeTag}
        - Key: "teamDL"
          Value: !Sub ${teamDlTag}
        - Key: "environment"
          Value: !Sub ${environmentTag}

  JenkinsAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${stackResourcesPrefix}-jenkins-${jenkinsUid}-elb
      Scheme: internal
      Type: application
      SecurityGroups: !Ref stackSecurityGroupIds
      Subnets: !Ref jenkinsAlbSubnets
      Tags:
        - Key: "Name"
          Value: !Sub ${stackResourcesPrefix}-jenkins-${jenkinsUid}-elb
        - Key: "systemCode"
          Value: !Sub ${systemCodeTag}
        - Key: "teamDL"
          Value: !Sub ${teamDlTag}
        - Key: "environment"
          Value: !Sub ${environmentTag}

  JenkinsAlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref stackVpcId
      Port: 8080
      HealthCheckPath: '/login'
      Protocol: HTTP
      HealthCheckPort: 8080
      HealthCheckTimeoutSeconds: 25
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200-299'
      Targets:
        - Id: !Ref JenkinsController
      TargetGroupAttributes:
        - Key: 'deregistration_delay.timeout_seconds'
          Value: '30'
      Tags:
        - Key: "Name"
          Value: !Sub ${stackResourcesPrefix}-jenkins-${jenkinsUid}-tg
        - Key: "systemCode"
          Value: !Sub ${systemCodeTag}
        - Key: "teamDL"
          Value: !Sub ${teamDlTag}
        - Key: "environment"
          Value: !Sub ${environmentTag}

  JenkinsAlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref JenkinsAlbTargetGroup
      LoadBalancerArn: !Ref JenkinsAlb
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref albListenerCertificateArn

Outputs:
  JenkinsAlbDnsName:
    Description: Jenkins ALB DNS record
    Value: !GetAtt JenkinsAlb.DNSName
