Description: "Creates secondary concept notification stream for concept updates in UPP"

Parameters:
  EnvironmentTag:
    Type: String
    Default: "dev"
  EnvironmentType:
    Type: String
    Default: "d"
  Region:
    Type: String
    Default: "us-east-1"

Resources:
  ConceptNotificationStream:
    Type: "AWS::Kinesis::Stream"
    Properties:
      Name: !Join [ "", ["upp-secondary-concept-notifications-", !Ref EnvironmentTag]]
      RetentionPeriodHours: 24
      ShardCount: 1
      Tags:
        - Key: "systemCode"
          Value: "upp"
        - Key: "teamDL"
          Value: "universal.publishing@ft.com"
        - Key: "environment"
          Value: !Ref EnvironmentType
        - Key: "description"
          Value: !Join ["", ["Secondary Concept Notifications Stream - ", !Ref EnvironmentTag]]
