#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

CONFIG_PATH="/config"
JENKINS_CONFIG="${CONFIG_PATH}/vars/${JENKINS_UID}.sh"

if [ ! -f "${JENKINS_CONFIG}" ]; then
  echo "No configuration for $JENKINS_UID exist at ${JENKINS_CONFIG}"
  exit 1
else
  set -o allexport
  # shellcheck source=/dev/null
  source "${JENKINS_CONFIG}"
  set +o allexport
fi

PACKER_TEMPLATE="${CONFIG_PATH}/packer/jenkins-controller.json"
export PROVISION_SCRIPT="${CONFIG_PATH}/packer/provision-jenkins-controller.sh"
export SYSCONFIG_JENKINS_TEMPLATE="${CONFIG_PATH}/packer/etc-sysconfig-jenkins-template.conf"
export BUILDER_INSTANCE_TYPE="t3.medium"

packer validate "${PACKER_TEMPLATE}"
packer build "${PACKER_TEMPLATE}"
