#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

CONFIG_PATH="/config"
CF_STACK_TEMPLATE="${CONFIG_PATH}/cloudformation/jenkins-controller.yaml"
JENKINS_CONFIG="${CONFIG_PATH}/vars/${JENKINS_UID}.sh"

if [ ! -f "${JENKINS_CONFIG}" ]; then
  echo "No configuration for $JENKINS_UID exist at ${JENKINS_CONFIG}"
  exit 1
else
  # shellcheck source=/dev/null
  source "${JENKINS_CONFIG}"
fi

aws cloudformation deploy \
  --stack-name "${CF_STACK_NAME}" \
  --region "${AWS_REGION}" \
  --template-file "${CF_STACK_TEMPLATE}" \
  --no-fail-on-empty-changeset \
  --parameter-overrides \
  stackResourcesPrefix="${RESOURCES_PREFIX}" \
  jenkinsUid="${JENKINS_UID}" \
  environmentTag="${ENVIRONMENT_TAG}" \
  systemCodeTag="${SYSTEM_CODE_TAG}" \
  teamDlTag="${TEAM_DL_TAG}" \
  jenkinsControllerInstanceType="${JENKINS_CONTROLLER_INSTANCE_TYPE}" \
  stackVpcId="${VPC_ID}" \
  jenkinsControllerSubnetId="${JENKINS_CONTROLLER_SUBNET_ID}" \
  jenkinsControllerKeyPairName="${JENKINS_CONTROLLER_KEYPAIR_NAME}" \
  jenkinsControllerImageId="${JENKINS_CONTROLLER_IMAGE_ID}" \
  jenkinsControllerAz="${JENKINS_CONTROLLER_AZ}" \
  jenkinsControllerJavaOptions="${JENKINS_CONTROLLER_JAVA_OPTIONS}" \
  stackSecurityGroupIds="${STACK_SECURITY_GROUP_IDS}" \
  jenkinsControllerEbsId="${JENKINS_CONTROLLER_EBS_ID}" \
  albListenerCertificateArn="${JENKINS_ALB_LISTENER_CERTIFICATE_ARN}" \
  jenkinsAlbSubnets="${JENKINS_ALB_SUBNETS}"

manage-cname "UPSERT"
