- hosts: 127.0.0.1
  connection: local

  vars:
    region: eu-west-1
    ami: ami-c26bcab1 #eu-west-1 HMV 835.9.0 (stable)
    #ami: ami-c3cae3b4 #eu-west-1 HMV CoreOS 815.0.0 (alpha)
    env: p
    ipcode: P295
    systemCode: "CoreOS-Universal-Publishing"
    description: "CoreOS-Universal-Publishing"
    teamDL: "universal.publishing.platform@ft.com"
    environment_tag: default
    instanceType: m4.large
  vars_files:
    - keys.yaml

  tasks:
    - template: src=/ansible/userdata/default_instance_user_data.yaml dest=/default.template

    - set_fact:
        persistent_tag: 1

    - template: src=/ansible/userdata/persistent_instance_user_data.yaml dest=/persistent1.template

    - set_fact:
        persistent_tag: 2

    - template: src=/ansible/userdata/persistent_instance_user_data.yaml dest=/persistent2.template

    - set_fact:
        persistent_tag: 3

    - template: src=/ansible/userdata/persistent_instance_user_data.yaml dest=/persistent3.template

